export const FETCH_EXERCISES_REQUEST = "FETCH_EXERCISES_REQUEST";
export const FETCH_EXERCISES_SUCCESS = "FETCH_EXERCISES_SUCCESS";
export const FETCH_EXERCISES_FAILURE = "FETCH_EXERCISES_FAILURE";

export const EVALUATE_ANSWER_REQUEST = "EVALUATE_ANSWER_REQUEST";
export const EVALUATE_ANSWER_SUCCESS = "EVALUATE_ANSWER_SUCCESS";
export const EVALUATE_ANSWER_FAILURE = "EVALUATE_ANSWER_FAILURE";
