export const UPDATE_PROGRESS_REQUEST = 'UPDATE_PROGRESS_REQUEST';
export const UPDATE_PROGRESS_SUCCESS = 'UPDATE_PROGRESS_SUCCESS';
export const UPDATE_PROGRESS_FAILURE = 'UPDATE_PROGRESS_FAILURE';

export const FETCH_PROGRESS_REQUEST = 'FETCH_PROGRESS_REQUEST';
export const FETCH_PROGRESS_SUCCESS = 'FETCH_PROGRESS_SUCCESS';
export const FETCH_PROGRESS_FAILURE = 'FETCH_PROGRESS_FAILURE';


export const FETCH_ALL_PROGRESS_REQUEST = 'FETCH_ALL_PROGRESS_REQUEST';
export const FETCH_ALL_PROGRESS_SUCCESS = 'FETCH_ALL_PROGRESS_SUCCESS';
export const FETCH_ALL_PROGRESS_FAILURE = 'FETCH_ALL_PROGRESS_FAILURE';